apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  selector:
    matchLabels:
      k8s-app: kafka-exporter
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter:latest
        args: [ --zookeeper.server=zookeeper-clusterip:2181] #[ --kafka.server={{ .Values.KafkaExporter.KafkaAddress }}]
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP