apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  selector:
    matchLabels:
      k8s-app: kafka-exporter
  replicas: 1
  template:
    spec:
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter
        args:
          [ '--kafka.server=kafka:9092' ]
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP