apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  selector:
    matchLabels:
      k8s-app: kafka-exporter
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter.v1.2.0
        args:
          [ '--kafka.server=kafka-svc:9092' ]
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP