{
 "title": "K8S / Cluster",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Specs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "Nodes" },
    {
     "expr": "sum(kube_pod_info * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))",
     "legendFormat": "Pods"
    },
    { "expr": "sum(kube_service_info)", "legendFormat": "Services" },
    {
     "expr": "sum(kube_persistentvolume_info)",
     "legendFormat": "PVCs"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Cpu Requested/Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))",
     "legendFormat": "Requested CPU"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "Total CPU"
    }
   ]
  },
  {
   "title": "Cluster Cpu Requested/Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1)) / sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Cluster Cpu Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"iowait\"}[5m])) / count(sum(node_cpu_seconds_total) BY (instance, cpu))",
     "legendFormat": "Cluster-cpu"
    }
   ]
  },
  {
   "title": "Cluster Memory Requested/Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))",
     "legendFormat": "Requested Memory"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Cluster Memory Requested/Total",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1)) / sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "Requested CPU"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(instance:node_memory_utilisation:ratio)",
     "legendFormat": "Cluster-memory"
    }
   ]
  },
  {
   "title": "Pod Allocation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1))",
     "legendFormat": "Pod Count"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "Allocatable pods"
    }
   ]
  },
  {
   "title": "Cluster Pods Running/Max Pods",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info * on(namespace, pod, cluster) group_left() max by(namespace, pod) (kube_pod_status_phase{phase=~\"Pending|Running\"} == 1)) / sum(kube_node_status_allocatable{resource=\"pods\"})",
     "legendFormat": "Pod Count"
    }
   ]
  },
  {
   "title": "Service list",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kube_service_info) by(service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(\nsum(max(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"} - node_filesystem_avail_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)) by (pod,namespace)\n/ scalar(sum(max(node_filesystem_size_bytes{fstype=~\"ext[234]|btrfs|xfs|zfs\"}) by (device,pod,namespace)))\n* on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{}\n)",
     "legendFormat": "Cluster-disk"
    }
   ]
  }
 ]
}