{
 "title": "Kafka Topic Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic name",
    "query": {
     "query": "label_values(kafka_log_log_size,topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total # of Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount)"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "graph",
   "gridPos": { "h": 10, "w": 13, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_messagesinpersec{}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_log_log_size{topic!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Total # of Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount)"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesinpersec{}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum without(instance) (rate(kafka_server_brokertopicmetrics_bytesoutpersec{topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalproducerequestspersec{}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Request per sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_totalfetchrequestspersec{topic!=\"\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Start Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "kafka_log_log_logstartoffset" }
   ]
  },
  {
   "title": "End Offset",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "kafka_log_log_logendoffset" }
   ]
  }
 ]
}