apiVersion: v1
kind: Service
metadata:
  name: { { .Release.Name } }-jmx-exporter
spec:
  ports:
  - name: http-metrics
    port: 5556
    protocol: TCP
    targetPort: 5556
  selector:
    k8s-app: jmx-exporter