apiVersion: v1
kind: Service
metadata:
  labels:
    name: event-exporter
  name: event-exporter
spec:
  ports:
    - name: http
      port: 9102
      targetPort: 9102
  selector:
    app: event-exporter